=== Victorhernandez05/ASIX/RA4 Activitat10. Material copy/biblioteca.dtd
<!ELEMENT biblioteca (comanda+)>
<!ELEMENT comanda (llibre+)>
<!ATTLIST comanda id ID #REQUIRED>
<!ELEMENT llibre (titol, autor, editorial, any, quantitat)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>

=== Victorhernandez05/ASIX/RA4 Activitat10. Material copy/biblioteca_erroni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
  <comanda id="C001">
    <llibre>
      <titol>Harry Potter i la pedra filosofal</titol>
      <autor>J.K. Rowling</autor>
      <editorial>Salamandra</editorial>
      <any>1998</any>
      <quantitat>3</quantitat>
    </llibre>
    <llibre>
      <titol>El senyor dels anells</titol>
      <autor>J.R.R. Tolkien</autor>
      <editorial>Minotauro</editorial>
      <quantitat>2</quantitat>
    </llibre>
  </comanda>
  <comanda id="C002">
    <llibre>
      <titol>El nom del vent</titol>
      <autor>Patrick Rothfuss</autor>
      <!-- Error: etiqueta <editor incorrecta -->
      <editor>Penguin Random House</editor>
      <any>2007</any>
      <quantitat>5</quantitat>
    </llibre>
  </comanda>
</biblioteca>
